on:
  push:
  workflow_dispatch:

jobs:
  repro:
    strategy:
      fail-fast: false
      matrix:
        version: [10.0.1, 10.0.8]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          path: effort

      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          repository: zzzprojects/nmemory
          path: nmemory

      - name: Install .NET Runtime
        run: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --runtime dotnet --version ${{ matrix.version }} --install-dir ./.dotnet
          ./dotnet-install.sh --version 10.0.101 --install-dir ./.dotnet
          echo "$GITHUB_WORKSPACE/.dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$GITHUB_WORKSPACE/.dotnet" >> $GITHUB_ENV

      - name: .NET Info
        working-directory: effort/reproduction
        run: |
          which dotnet
          dotnet --info

      - name: Build
        working-directory: effort/reproduction
        run: dotnet build -c Debug

      - name: Test
        working-directory: effort/reproduction
        shell: pwsh
        run: |
          for ($i = 0; $i -lt 50; $i++) {
            Write-Host "Run #$($i + 1)"
            
            dotnet run -c Debug --no-build

            if ($LASTEXITCODE -ne 0) {
              throw "Run #$($i + 1) failed with exit code $LASTEXITCODE"
            }
          }
